// Regenerates src/cpp_lsp_std_names.cpp: every name the C++ standard
// library declares, which is what mep's own C++ language server
// (src/cpp_lsp.cpp) checks an unresolved identifier against before it
// dares report it as undefined.
//
// Built and run by scripts/gen_cpp_std_names.sh, which preprocesses a
// translation unit including every standard header with the real
// compiler and feeds the result in here. The extraction is done by mep's
// own parser (src/cpp_ast.cpp) rather than by a regex: the input is a
// couple of hundred thousand lines of real C++, and anything less than a
// parser gets the namespaces wrong.
//
// The generated file is committed, so building mep never needs a
// compiler's headers. Re-run this only to refresh the list against a
// newer standard library; the output is sorted (byte order, LC_COLLATE=C)
// because the array is binary-searched.

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <set>
#include <string>
#include <vector>

#include "cpp_ast.h"

namespace {

// Internal names the standard library is full of: everything reserved to
// the implementation, plus the handful of public names that are not
// useful to offer.
bool IsInternalName(const std::string &name) {
    if (name.empty() || name.size() > 60) return true;
    if (name[0] == '_') return true;
    if (name.rfind("operator", 0) == 0) return true;
    return false;
}

void Collect(const CppNode *node, bool in_std, std::set<std::string> *out) {
    if (node == nullptr) return;
    for (const CppNodePtr &child : node->body) {
        const CppNode *decl = child.get();
        if (decl == nullptr) continue;
        switch (decl->kind) {
            case CppNodeKind::Namespace:
                // Everything under `std` counts, including its inline
                // versioning namespaces (`std::__8`, `std::ranges`, ...).
                Collect(decl, in_std || decl->name == "std", out);
                if (in_std && !decl->name.empty() && !IsInternalName(decl->name)) out->insert(decl->name);
                break;
            case CppNodeKind::LinkageSpec:
                Collect(decl, in_std, out);
                break;
            case CppNodeKind::Class:
            case CppNodeKind::Enum:
                if (!IsInternalName(decl->name)) out->insert(decl->name);
                // A class's members are not global names, but an enum's
                // enumerators are (for an unscoped enum).
                if (decl->kind == CppNodeKind::Enum) Collect(decl, in_std, out);
                break;
            case CppNodeKind::Enumerator:
            case CppNodeKind::Function:
            case CppNodeKind::Variable:
            case CppNodeKind::Typedef:
            case CppNodeKind::UsingAlias:
            case CppNodeKind::Concept:
                if (!IsInternalName(decl->name)) out->insert(decl->name);
                break;
            case CppNodeKind::UsingDecl:
                if (!IsInternalName(decl->name)) out->insert(decl->name);
                break;
            default:
                break;
        }
    }
}

}  // namespace

int main(int argc, char **argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: gen_cpp_std_names <preprocessed.ii> <output.cpp> [macros.txt]\n");
        return 2;
    }
    std::vector<std::string> lines;
    {
        std::ifstream in(argv[1]);
        if (!in) {
            std::fprintf(stderr, "cannot read %s\n", argv[1]);
            return 2;
        }
        std::string line;
        while (std::getline(in, line)) lines.push_back(line);
    }
    std::fprintf(stderr, "parsing %zu lines...\n", lines.size());
    const CppParseResult parsed = ParseCpp(lines);
    std::fprintf(stderr, "%zu syntax errors\n", parsed.errors.size());

    std::set<std::string> names;
    Collect(parsed.unit.get(), false, &names);

    // The macros the standard headers define (`SEEK_SET`, `EOF`,
    // `INT_MAX`, `errno`): preprocessing removed them from the stream
    // above, so they come from the compiler's own `-dM` dump instead.
    // Without them every `std::fseek(f, 0, SEEK_END)` is an undefined
    // name.
    if (argc > 3) {
        std::ifstream macros(argv[3]);
        std::string name;
        size_t macro_count = 0;
        while (macros >> name) {
            if (IsInternalName(name)) continue;
            names.insert(name);
            macro_count++;
        }
        std::fprintf(stderr, "%zu macro names\n", macro_count);
    }

    std::ofstream out(argv[2]);
    if (!out) {
        std::fprintf(stderr, "cannot write %s\n", argv[2]);
        return 2;
    }
    out << "// Generated by scripts/gen_cpp_std_names.sh -- do not edit.\n";
    out << "//\n";
    out << "// Every name the C++ standard library declares, extracted from a real\n";
    out << "// preprocessed translation unit that includes every standard header (see\n";
    out << "// scripts/gen_cpp_std_names.cpp). mep's C++ language server checks an\n";
    out << "// unresolved identifier against this list before reporting it as undefined,\n";
    out << "// and offers it as a completion after `std::`.\n";
    out << "//\n";
    out << "// Sorted in byte order (LC_COLLATE=C): the array is binary-searched.\n";
    out << "\n";
    out << "extern const char *const kCppStdNames[];\n";
    out << "extern const unsigned kCppStdNameCount;\n\n";
    out << "const char *const kCppStdNames[] = {\n";
    size_t column = 0;
    out << "    ";
    for (const std::string &name : names) {
        const std::string entry = "\"" + name + "\", ";
        if (column + entry.size() > 96) {
            out << "\n    ";
            column = 0;
        }
        out << entry;
        column += entry.size();
    }
    out << "\n};\n\n";
    out << "const unsigned kCppStdNameCount = " << names.size() << "u;\n";
    std::fprintf(stderr, "wrote %zu names to %s\n", names.size(), argv[2]);
    return 0;
}
