#!/usr/bin/env Rscript
# Regenerates src/r_lsp_base_names.cpp: every name the base R distribution
# exports, which is what mep's own R language server (src/r_lsp.cpp) checks
# an unresolved identifier against before it dares report it as undefined.
#
# Run from the repository root, in an environment with R on PATH:
#   nix develop --command Rscript scripts/gen_r_names.R
#
# The generated file is committed, so building mep never needs R. Re-run
# this only to refresh the list against a newer R; the output is sorted,
# so the diff stays readable.

pkgs <- c("base", "stats", "utils", "graphics", "grDevices", "methods", "tools",
          "datasets", "parallel", "compiler", "grid", "splines", "stats4")

exported <- unlist(lapply(pkgs, function(p) {
  if (!requireNamespace(p, quietly = TRUE)) return(character())
  tryCatch(getNamespaceExports(p), error = function(e) character())
}))

# The data sets a script may name without ever assigning them (iris, mtcars,
# ...) are not namespace exports, so they are collected separately.
data_sets <- tryCatch({
  items <- utils::data(package = pkgs)$results[, "Item"]
  sub(" .*", "", items)
}, error = function(e) character())

reserved <- c("if", "else", "for", "while", "repeat", "function", "break", "next", "in",
              "TRUE", "FALSE", "NULL", "NA", "Inf", "NaN",
              "NA_integer_", "NA_real_", "NA_character_")

# C collation, not the user's locale: the generated array is binary-searched
# by byte comparison in C++, so it has to be sorted the same way.
invisible(Sys.setlocale("LC_COLLATE", "C"))
names <- sort(unique(c(exported, data_sets)))
names <- names[grepl("^[A-Za-z][A-Za-z0-9._]*$", names)]  # syntactic, non-dotted
names <- setdiff(names, reserved)

out <- file("src/r_lsp_base_names.cpp", "w")
writeLines(c(
  "// Generated by scripts/gen_r_names.R -- do not edit by hand.",
  "//",
  "// Every syntactic name the base R distribution exports, plus the data sets",
  "// it ships, as of the R version named below. mep's own R language server",
  "// checks an unresolved identifier against this list before reporting it:",
  "// the curated table in r_lsp_vocab.cpp carries signatures and documentation",
  "// for a few hundred functions, while this one exists purely so that calling",
  "// something real -- diff(), rle(), bitwAnd(), iris -- is never reported as a",
  "// mistake just because nobody wrote a doc string for it here.",
  "//",
  paste0("// Source: ", R.version.string, ", packages ", paste(pkgs, collapse = ", "), "."),
  "",
  "#include <algorithm>",
  "#include <string>",
  "#include <vector>",
  "",
  "#include \"r_lsp.h\"",
  "",
  "namespace {",
  "",
  "// Sorted, so the lookup below can binary-search it.",
  "const char *const kBaseNames[] = {"), con = out)
writeLines(paste0("    \"", names, "\","), con = out)
writeLines(c(
  "};",
  "",
  "}  // namespace",
  "",
  "bool RLspIsBaseName(const std::string &name) {",
  "    const auto end = kBaseNames + sizeof(kBaseNames) / sizeof(kBaseNames[0]);",
  "    const auto at = std::lower_bound(kBaseNames, end, name,",
  "                                     [](const char *a, const std::string &b) { return b.compare(a) > 0; });",
  "    return at != end && name == *at;",
  "}",
  "",
  "const std::vector<std::string> &RLspBaseNameList() {",
  "    static const std::vector<std::string> names(kBaseNames,",
  "                                                kBaseNames + sizeof(kBaseNames) / sizeof(kBaseNames[0]));",
  "    return names;",
  "}"), con = out)
close(out)
cat("wrote src/r_lsp_base_names.cpp:", length(names), "names\n")
