#ifndef MEP_C_LSP_STD_NAMES_H
#define MEP_C_LSP_STD_NAMES_H

#include <cstddef>

// The interface to src/c_lsp_std_names.cpp, which is generated by
// scripts/gen_c_names.py out of the real C standard library and POSIX
// headers. See that script's header comment for why it is generated
// rather than written: a server that remembers the standard library
// gets it wrong, and gets it wrong in the direction that invents
// diagnostics.

// One public declaration, as the generator reconstructed it.
struct CStdDecl {
    const char *name;    // "printf"
    const char *header;  // "stdio.h"
    const char *detail;  // "int printf(const char *format, ...)"
};

// Every identifier the covered headers introduce, sorted by byte
// comparison (implementation names included -- this array answers
// "could this name have come from a header", and `__errno_location`
// could).
extern const char *const kCStdNames[];
extern const size_t kCStdNameCount;

// The public subset, sorted by name, with the header each comes from.
extern const CStdDecl kCStdDecls[];
extern const size_t kCStdDeclCount;

// The headers themselves, standard set first and then POSIX.
extern const char *const kCStdHeaders[];
extern const size_t kCStdHeaderCount;

#endif  // MEP_C_LSP_STD_NAMES_H
