#include "collab_crdt.h"
#include "json.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <random>

namespace {
// Always active regardless of NDEBUG -- this project's own default
// CMAKE_BUILD_TYPE is Release (see CMakeLists.txt), which defines NDEBUG,
// and NDEBUG compiles assert(...) to nothing at all, including any
// side-effecting call inside it. A plain assert() here would silently
// skip calling Restore()/comparing Text() in exactly that build, and this
// test would report success regardless of whether the CRDT logic actually
// worked (see agent_rpc_test.cpp's own CHECK() for the same reasoning --
// this mirrors it).
/**
 * @brief Prints a CHECK-failure message (with file/line) to stderr and aborts the process.
 * @param expr The source text of the failed condition.
 * @param file The source file the check ran in.
 * @param line The source line the check ran on.
 */
void CheckFailed(const char *expr, const char *file, int line) {
    std::fprintf(stderr, "CHECK FAILED: %s at %s:%d\n", expr, file, line);
    std::fflush(stderr);
    std::abort();
}
}  // namespace
#define CHECK(cond) ((cond) ? (void)0 : CheckFailed(#cond, __FILE__, __LINE__))

using mep::collab::CrdtOperation;
using mep::collab::TextCrdt;

/**
 * @brief Exercises TextCrdt convergence between two replicas (concurrent inserts, a delete, and snapshot/restore round-trip), asserting their text stays in sync.
 */
void TestBasicConvergence() {
    TextCrdt a("alice"), b("bob");
    const auto hello = a.Insert(0, "hello"); b.Apply(hello);
    const auto left = a.Insert(5, " A"), right = b.Insert(5, " B");
    a.Apply(right); b.Apply(left); CHECK(a.Text() == b.Text());
    const auto erase = a.Erase(0, 1); b.Apply(erase); CHECK(a.Text() == b.Text());
    Json snapshot = a.Snapshot();
    TextCrdt restored; CHECK(restored.Restore(snapshot)); CHECK(restored.Text() == a.Text());
}

/**
 * @brief CRDT_PERFORMANCE_PLAN.md Phase 2: many replicas (not just 2), each doing a mix of random
 * inserts/deletes at random positions in its own (locally up-to-date) view, interleaved with every other
 * replica's ops delivered in strict generation order -- the scale of correctness testing the Phase-2 treap
 * rewrite needed that the original 2-replica fixed example didn't cover.
 */
void TestManySitesConvergence() {
    constexpr int kSites = 6;
    constexpr int kOpsPerSite = 150;
    std::mt19937 rng(1234);
    std::vector<TextCrdt> replicas;
    for (int i = 0; i < kSites; i++) replicas.emplace_back("site" + std::to_string(i));
    std::vector<CrdtOperation> all_ops;
    for (int round = 0; round < kOpsPerSite; round++) {
        for (int i = 0; i < kSites; i++) {
            TextCrdt &r = replicas[static_cast<size_t>(i)];
            size_t size = r.VisibleSize();
            std::vector<CrdtOperation> ops;
            if (size == 0 || rng() % 3 != 0) {
                size_t pos = size == 0 ? 0 : rng() % (size + 1);
                std::string text(1 + rng() % 4, static_cast<char>('a' + rng() % 26));
                ops = r.Insert(pos, text);
            } else {
                size_t pos = rng() % size;
                ops = r.Erase(pos, 1 + rng() % std::min<size_t>(3, size - pos));
            }
            for (auto &op : ops) all_ops.push_back(op);
        }
    }
    for (int i = 0; i < kSites; i++) {
        for (const auto &op : all_ops) replicas[static_cast<size_t>(i)].Apply(op);
    }
    const std::string &expected = replicas[0].Text();
    for (int i = 1; i < kSites; i++) {
        CHECK(replicas[static_cast<size_t>(i)].Text() == expected);
        CHECK(replicas[static_cast<size_t>(i)].VisibleSize() == expected.size());
    }
}

/**
 * @brief CRDT_PERFORMANCE_PLAN.md Phase 2: applies a large batch of operations (generated by two
 * interleaved-writing replicas) to a fresh replica in randomly shuffled order, exercising the
 * pending_inserts_/pending_deletes_ out-of-order-arrival buffering explicitly (a relay/network can deliver
 * ops in any order) -- checks the shuffled replica still converges to the same text as one that received
 * everything in generation order.
 */
void TestOutOfOrderDelivery() {
    std::mt19937 rng(5678);
    TextCrdt a("alice"), b("bob");
    std::vector<CrdtOperation> all_ops;
    for (int round = 0; round < 80; round++) {
        auto ops_a = a.Insert(rng() % (a.VisibleSize() + 1), std::string(1, static_cast<char>('A' + round % 26)));
        for (auto &op : ops_a) all_ops.push_back(op);
        auto ops_b = b.Insert(rng() % (b.VisibleSize() + 1), std::string(1, static_cast<char>('a' + round % 26)));
        for (auto &op : ops_b) all_ops.push_back(op);
        if (round % 5 == 0 && a.VisibleSize() > 0) {
            auto del = a.Erase(rng() % a.VisibleSize(), 1);
            for (auto &op : del) all_ops.push_back(op);
        }
    }

    // In-order reference: a fresh replica fed every op in generation order.
    TextCrdt in_order("checker1");
    in_order.Apply(all_ops);

    // Shuffled: a fresh replica fed the exact same ops in randomized order.
    std::vector<CrdtOperation> shuffled = all_ops;
    std::shuffle(shuffled.begin(), shuffled.end(), rng);
    TextCrdt out_of_order("checker2");
    out_of_order.Apply(shuffled);

    CHECK(in_order.Text() == out_of_order.Text());
    CHECK(in_order.VisibleSize() == out_of_order.VisibleSize());
}

/**
 * @brief CRDT_PERFORMANCE_PLAN.md Phase 2: two replicas each insert several thousand characters (well past
 * the ~60k-character point the pre-rewrite recursive VisibleIds() used to stack-overflow crash at for a
 * single sequential run), interleaved, then converge -- a real-scale regression check for that crash and for
 * ordinary large-document correctness.
 */
void TestLargeSequentialConvergence() {
    TextCrdt a("alice"), b("bob");
    constexpr size_t kChunk = 20000;
    auto ops_a = a.Insert(0, std::string(kChunk, 'x'));
    auto ops_b = b.Insert(0, std::string(kChunk, 'y'));
    b.Apply(ops_a);
    a.Apply(ops_b);
    CHECK(a.Text() == b.Text());
    CHECK(a.VisibleSize() == kChunk * 2);
    CHECK(b.VisibleSize() == kChunk * 2);
}

/**
 * @brief CRDT_PERFORMANCE_PLAN.md Phase 3 regression test: a second Insert() at an anchor an earlier Insert()
 * already used (the common case of editing at the same position more than once, e.g. twice at position 0)
 * must land at the requested position, not get sequenced after that earlier sibling's entire subtree.
 * TestManySitesConvergence/TestOutOfOrderDelivery above never caught this: they only assert replicas agree
 * with *each other*, which a deterministic-but-wrong tie-break still satisfies -- this checks the actual text
 * a single replica produces.
 */
void TestRepeatedAnchorInsertHonorsPosition() {
    TextCrdt doc("tester");
    doc.Insert(0, "ABCDEF");
    doc.Erase(0, 3);
    doc.Insert(0, "XYZ");
    CHECK(doc.Text() == "XYZDEF");

    TextCrdt doc2("tester2");
    doc2.Insert(0, "ABCDEF");
    doc2.Erase(2, 2);
    doc2.Insert(2, "XY");
    CHECK(doc2.Text() == "ABXYEF");
}

int main() {
    TestBasicConvergence();
    TestManySitesConvergence();
    TestOutOfOrderDelivery();
    TestLargeSequentialConvergence();
    TestRepeatedAnchorInsertHonorsPosition();
    std::cout << "collab_crdt_test passed\n";
}
