// The R vocabulary mep's own R language server knows: the functions of
// the base distribution with their real formals, plus reserved words,
// constants, operators, roxygen2 tags and package names.
//
// Hand-maintained rather than generated from an R installation, for the
// same reason the whole server is in-house: `mep-r-lsp` has to answer a
// hover on `mean()` on a machine with no R on it at all. The formals are
// written exactly as R declares them (`?mean` and friends), because
// signature help, the unknown-argument check and the argument-name
// completions all read them: an entry whose formals drift from R's own
// is worse than no entry, so anything uncertain is left out instead of
// guessed.
//
// Every entry's formals were checked against a real R 4.6 installation
// (`formals(args(fn))`) while this table was written. Four of them --
// legend(), pdf(), source() and library(), whose real formal lists run to
// twenty arguments and more -- deliberately list the arguments people
// actually pass and end in `...`; that is the conservative direction,
// because an entry ending in `...` is never argument-checked.
//
// Coverage is "what a person writing R actually types", not "everything
// exported": the arithmetic/vector/apply/string/IO core, the common
// statistics, the base graphics people still use, and the S4/R5 plumbing.
// Entries are grouped by topic rather than sorted, so lookups go through
// the name index RLspFindFunction builds once.
// A name not in here is simply not annotated -- it is never reported as
// an error, because RLspDiagnostics only trusts this table for
// *positive* knowledge (see r_lsp.cpp's own note on that).

#include <map>
#include <string>
#include <vector>

#include "r_lsp.h"

namespace {

// --- Functions --------------------------------------------------------

const std::vector<RLspFunctionEntry> kFunctions = {
    // base: the language itself
    {"c", "base", "...", "Combines its arguments into a vector or list."},
    {"list", "base", "...", "Builds a list from its arguments."},
    {"vector", "base", "mode = \"logical\", length = 0", "Creates a vector of a given mode and length."},
    {"length", "base", "x", "The number of elements in a vector, list or other object."},
    {"names", "base", "x", "The names attribute of an object."},
    {"attr", "base", "x, which, exact = FALSE", "Gets one attribute of an object."},
    {"attributes", "base", "x", "All attributes of an object, as a list."},
    {"class", "base", "x", "The class attribute of an object."},
    {"inherits", "base", "x, what, which = FALSE", "Tests whether an object inherits from a class."},
    {"structure", "base", ".Data, ...", "Returns an object with attributes set."},
    {"identical", "base", "x, y, num.eq = TRUE, single.NA = TRUE, attrib.as.set = TRUE, ignore.bytecode = TRUE, ignore.environment = FALSE, ignore.srcref = TRUE, extptr.as.ref = FALSE", "Exact equality of two objects, with no coercion."},
    {"all.equal", "base", "target, current, ...", "Near equality of two objects, within a tolerance."},
    {"is.null", "base", "x", "Tests for NULL."},
    {"is.na", "base", "x", "Elementwise test for NA (the only correct way to ask)."},
    {"is.nan", "base", "x", "Elementwise test for NaN."},
    {"is.finite", "base", "x", "Elementwise test for a finite number."},
    {"is.infinite", "base", "x", "Elementwise test for Inf or -Inf."},
    {"is.numeric", "base", "x", "Tests whether an object is numeric."},
    {"is.character", "base", "x", "Tests whether an object is a character vector."},
    {"is.logical", "base", "x", "Tests whether an object is a logical vector."},
    {"is.function", "base", "x", "Tests whether an object is a function."},
    {"is.list", "base", "x", "Tests whether an object is a list."},
    {"is.vector", "base", "x, mode = \"any\"", "Tests for a vector with no attributes but names."},
    {"is.matrix", "base", "x", "Tests whether an object is a matrix."},
    {"is.data.frame", "base", "x", "Tests whether an object is a data frame."},
    {"is.element", "base", "el, set", "Tests membership, the functional form of %in%."},
    {"as.numeric", "base", "x, ...", "Coerces to a numeric (double) vector."},
    {"as.integer", "base", "x, ...", "Coerces to an integer vector, truncating toward zero."},
    {"as.character", "base", "x, ...", "Coerces to a character vector."},
    {"as.logical", "base", "x, ...", "Coerces to a logical vector."},
    {"as.factor", "base", "x", "Coerces to a factor."},
    {"as.vector", "base", "x, mode = \"any\"", "Coerces to a vector, dropping attributes."},
    {"as.list", "base", "x, ...", "Coerces to a list."},
    {"as.matrix", "base", "x, ...", "Coerces to a matrix."},
    {"as.data.frame", "base", "x, row.names = NULL, optional = FALSE, ...", "Coerces to a data frame."},
    {"factor", "base", "x = character(), levels, labels = levels, exclude = NA, ordered = is.ordered(x), nmax = NA",
     "Creates a factor from a vector, with an explicit level order."},
    {"levels", "base", "x", "The levels of a factor."},
    {"nlevels", "base", "x", "The number of levels of a factor."},
    {"numeric", "base", "length = 0", "A double vector of a given length, filled with 0."},
    {"integer", "base", "length = 0", "An integer vector of a given length, filled with 0L."},
    {"character", "base", "length = 0", "A character vector of a given length, filled with \"\"."},
    {"logical", "base", "length = 0", "A logical vector of a given length, filled with FALSE."},
    {"matrix", "base", "data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL",
     "Creates a matrix from a vector, filling by column unless byrow is TRUE."},
    {"array", "base", "data = NA, dim = length(data), dimnames = NULL", "Creates an array of arbitrary dimension."},
    {"data.frame", "base", "..., row.names = NULL, check.rows = FALSE, check.names = TRUE, stringsAsFactors = FALSE",
     "Creates a data frame from equal-length columns."},
    {"dim", "base", "x", "The dimensions of a matrix, array or data frame."},
    {"nrow", "base", "x", "The number of rows."},
    {"ncol", "base", "x", "The number of columns."},
    {"NROW", "base", "x", "The number of rows, treating a vector as a one-column matrix."},
    {"NCOL", "base", "x", "The number of columns, treating a vector as a one-column matrix."},
    {"rownames", "base", "x, do.NULL = TRUE, prefix = \"row\"", "The row names of a matrix or data frame."},
    {"colnames", "base", "x, do.NULL = TRUE, prefix = \"col\"", "The column names of a matrix or data frame."},
    {"dimnames", "base", "x", "The dimension names of an array."},
    {"cbind", "base", "..., deparse.level = 1", "Binds objects together as columns."},
    {"rbind", "base", "..., deparse.level = 1", "Binds objects together as rows."},
    {"t", "base", "x", "Matrix transpose."},
    {"head", "utils", "x, n = 6L, ...", "The first n elements or rows."},
    {"tail", "utils", "x, n = 6L, ...", "The last n elements or rows."},
    {"rev", "base", "x", "Reverses a vector."},
    {"sort", "base", "x, decreasing = FALSE, ...", "Sorts a vector, dropping NAs by default."},
    {"order", "base", "..., na.last = TRUE, decreasing = FALSE", "The permutation that sorts its arguments."},
    {"rank", "base", "x, na.last = TRUE, ties.method = c(\"average\", \"first\", \"last\", \"random\", \"max\", \"min\")",
     "The ranks of a vector's elements."},
    {"unique", "base", "x, incomparables = FALSE, ...", "Drops duplicated elements, keeping the first."},
    {"duplicated", "base", "x, incomparables = FALSE, ...", "Marks elements that have appeared before."},
    {"rle", "base", "x", "Run-length encoding of a vector."},
    {"which", "base", "x, arr.ind = FALSE, useNames = TRUE", "The indices where a logical vector is TRUE."},
    {"which.max", "base", "x", "The index of the (first) maximum."},
    {"which.min", "base", "x", "The index of the (first) minimum."},
    {"any", "base", "..., na.rm = FALSE", "TRUE if any element is TRUE."},
    {"all", "base", "..., na.rm = FALSE", "TRUE if every element is TRUE."},
    {"xor", "base", "x, y", "Elementwise exclusive or."},
    {"isTRUE", "base", "x", "TRUE only for a length-one TRUE, with no coercion."},
    {"isFALSE", "base", "x", "TRUE only for a length-one FALSE, with no coercion."},
    {"ifelse", "base", "test, yes, no", "Vectorized choice between two vectors, elementwise."},
    {"switch", "base", "EXPR, ...", "Chooses one of several expressions by name or position."},
    {"seq", "base", "from = 1, to = 1, by = ((to - from)/(length.out - 1)), length.out = NULL, along.with = NULL, ...",
     "A regular sequence."},
    {"seq_len", "base", "length.out", "The sequence 1..n, correct when n is zero."},
    {"seq_along", "base", "along.with", "The sequence 1..length(x), correct when x is empty."},
    {"rep", "base", "x, ...", "Repeats a vector, by `times`, `each` or `length.out`."},
    {"rep_len", "base", "x, length.out", "Repeats a vector to exactly a given length."},
    {"append", "base", "x, values, after = length(x)", "Inserts values into a vector."},
    {"setdiff", "base", "x, y", "Elements of x that are not in y."},
    {"union", "base", "x, y", "The union of two vectors, de-duplicated."},
    {"intersect", "base", "x, y", "The elements common to two vectors."},
    {"match", "base", "x, table, nomatch = NA_integer_, incomparables = NULL",
     "The position of each x in table, NA where absent."},
    {"do.call", "base", "what, args, quote = FALSE, envir = parent.frame()",
     "Calls a function with an argument list built at run time."},
    {"Reduce", "base", "f, x, init, right = FALSE, accumulate = FALSE", "Folds a binary function over a list."},
    {"Filter", "base", "f, x", "Keeps the elements for which a predicate is TRUE."},
    {"Map", "base", "f, ...", "mapply with SIMPLIFY = FALSE: always returns a list."},
    {"Negate", "base", "f", "Returns a function computing the logical negation of f."},
    {"Recall", "base", "...", "Calls the enclosing function again, by whatever name it has."},
    {"lapply", "base", "X, FUN, ...", "Applies a function to each element, always returning a list."},
    {"sapply", "base", "X, FUN, ..., simplify = TRUE, USE.NAMES = TRUE",
     "lapply that simplifies its result -- to a vector, a matrix, or a list, depending on the data."},
    {"vapply", "base", "X, FUN, FUN.VALUE, ..., USE.NAMES = TRUE",
     "sapply with the result type declared up front, so it cannot surprise you."},
    {"mapply", "base", "FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE",
     "Applies a function over several vectors in parallel."},
    {"apply", "base", "X, MARGIN, FUN, ..., simplify = TRUE", "Applies a function over the margins of an array."},
    {"tapply", "base", "X, INDEX, FUN = NULL, ..., default = NA, simplify = TRUE",
     "Applies a function to each group of a ragged array."},
    {"rapply", "base", "object, f, classes = \"ANY\", deflt = NULL, how = c(\"unlist\", \"replace\", \"list\"), ...",
     "Applies a function recursively through a nested list."},
    {"outer", "base", "X, Y, FUN = \"*\", ...", "The outer product of two vectors under a function."},
    {"unlist", "base", "x, recursive = TRUE, use.names = TRUE", "Flattens a list to a vector."},
    {"split", "base", "x, f, drop = FALSE, ...", "Splits a vector or data frame into groups by a factor."},
    {"stopifnot", "base", "...", "Stops unless every argument is all-TRUE."},
    {"stop", "base", "..., call. = TRUE, domain = NULL", "Raises an error and unwinds."},
    {"warning", "base", "..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE, domain = NULL",
     "Raises a warning without unwinding."},
    {"message", "base", "..., domain = NULL, appendLF = TRUE", "Writes a diagnostic message to stderr."},
    {"signalCondition", "base", "cond", "Signals a condition object."},
    {"tryCatch", "base", "expr, ..., finally", "Evaluates an expression, handling conditions it signals."},
    {"try", "base", "expr, silent = FALSE, outFile = getOption(\"try.outFile\", default = stderr())",
     "Evaluates an expression, returning a try-error object instead of stopping."},
    {"withCallingHandlers", "base", "expr, ...", "Handles conditions without unwinding the stack."},
    {"on.exit", "base", "expr = NULL, add = FALSE, after = TRUE", "Registers an expression to run when the function exits."},
    {"invisible", "base", "x = NULL", "Returns a value that is not auto-printed."},
    {"suppressWarnings", "base", "expr, classes = \"warning\"", "Evaluates an expression with warnings muffled."},
    {"suppressMessages", "base", "expr, classes = \"message\"", "Evaluates an expression with messages muffled."},
    {"conditionMessage", "base", "c", "The message of a condition object."},
    {"simpleError", "base", "message, call = NULL", "Builds a plain error condition object."},
    {"print", "base", "x, ...", "Prints an object, dispatching on its class."},
    {"cat", "base", "..., file = \"\", sep = \" \", fill = FALSE, labels = NULL, append = FALSE",
     "Writes its arguments out with no quoting or line breaks of its own."},
    {"format", "base", "x, ...", "Formats an object for printing."},
    {"formatC", "base", "x, width = 0L, digits = NULL, format = NULL, flag = \"\", mode = NULL, big.mark = \"\"",
     "C-style formatting of numbers."},
    {"sprintf", "base", "fmt, ...", "C-style string formatting, vectorized over its arguments."},
    {"paste", "base", "..., sep = \" \", collapse = NULL, recycle0 = FALSE", "Joins strings, with a space by default."},
    {"paste0", "base", "..., collapse = NULL, recycle0 = FALSE", "paste with sep = \"\"."},
    {"toString", "base", "x, ...", "Collapses a vector into one comma-separated string."},
    {"nchar", "base", "x, type = \"chars\", allowNA = FALSE, keepNA = NA", "The number of characters in each string."},
    {"substr", "base", "x, start, stop", "A substring by character position."},
    {"substring", "base", "text, first, last = 1000000L", "Substrings, recycling over its arguments."},
    {"strsplit", "base", "x, split, fixed = FALSE, perl = FALSE, useBytes = FALSE",
     "Splits each string on a pattern, returning a list."},
    {"sub", "base", "pattern, replacement, x, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE",
     "Replaces the first match of a pattern in each string."},
    {"gsub", "base", "pattern, replacement, x, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE",
     "Replaces every match of a pattern in each string."},
    {"grepl", "base", "pattern, x, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE",
     "TRUE for each string that matches a pattern."},
    {"grep", "base", "pattern, x, ignore.case = FALSE, perl = FALSE, value = FALSE, fixed = FALSE, useBytes = FALSE, invert = FALSE",
     "The indices (or values) of the strings matching a pattern."},
    {"regmatches", "base", "x, m, invert = FALSE", "Extracts the matched substrings found by regexpr/gregexpr."},
    {"regexpr", "base", "pattern, text, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE",
     "The position of the first match in each string."},
    {"gregexpr", "base", "pattern, text, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE",
     "The positions of every match in each string."},
    {"startsWith", "base", "x, prefix", "TRUE for each string starting with a prefix."},
    {"endsWith", "base", "x, suffix", "TRUE for each string ending with a suffix."},
    {"trimws", "base", "x, which = c(\"both\", \"left\", \"right\"), whitespace = \"[ \\t\\r\\n]\"",
     "Strips leading and trailing whitespace."},
    {"toupper", "base", "x", "Converts to upper case."},
    {"tolower", "base", "x", "Converts to lower case."},
    {"chartr", "base", "old, new, x", "Translates characters one for one."},
    {"strtoi", "base", "x, base = 10L", "Parses strings as integers in a given base."},
    {"abs", "base", "x", "Absolute value."},
    {"sqrt", "base", "x", "Square root."},
    {"exp", "base", "x", "The exponential function."},
    {"log", "base", "x, base = exp(1)", "Logarithm, natural unless a base is given."},
    {"log2", "base", "x", "Base-2 logarithm."},
    {"log10", "base", "x", "Base-10 logarithm."},
    {"log1p", "base", "x", "log(1 + x), accurate for small x."},
    {"expm1", "base", "x", "exp(x) - 1, accurate for small x."},
    {"sin", "base", "x", "Sine, in radians."},
    {"cos", "base", "x", "Cosine, in radians."},
    {"tan", "base", "x", "Tangent, in radians."},
    {"asin", "base", "x", "Arc sine."},
    {"acos", "base", "x", "Arc cosine."},
    {"atan", "base", "x", "Arc tangent."},
    {"atan2", "base", "y, x", "Arc tangent of y/x, using the signs to pick the quadrant."},
    {"floor", "base", "x", "Rounds down to an integer value."},
    {"ceiling", "base", "x", "Rounds up to an integer value."},
    {"round", "base", "x, digits = 0, ...", "Rounds to a number of digits, half to even."},
    {"signif", "base", "x, digits = 6", "Rounds to a number of significant digits."},
    {"trunc", "base", "x, ...", "Truncates toward zero."},
    {"sign", "base", "x", "-1, 0 or 1, elementwise."},
    {"sum", "base", "..., na.rm = FALSE", "Sum of all the values in its arguments."},
    {"prod", "base", "..., na.rm = FALSE", "Product of all the values in its arguments."},
    {"cumsum", "base", "x", "Cumulative sum."},
    {"cumprod", "base", "x", "Cumulative product."},
    {"cummax", "base", "x", "Cumulative maximum."},
    {"cummin", "base", "x", "Cumulative minimum."},
    {"max", "base", "..., na.rm = FALSE", "The largest value."},
    {"min", "base", "..., na.rm = FALSE", "The smallest value."},
    {"pmax", "base", "..., na.rm = FALSE", "Elementwise maximum across vectors."},
    {"pmin", "base", "..., na.rm = FALSE", "Elementwise minimum across vectors."},
    {"range", "base", "..., na.rm = FALSE", "The minimum and maximum, as a length-two vector."},
    {"mean", "base", "x, ...", "Arithmetic mean; pass na.rm = TRUE to drop NAs."},
    {"colSums", "base", "x, na.rm = FALSE, dims = 1", "Column sums of a matrix or data frame."},
    {"rowSums", "base", "x, na.rm = FALSE, dims = 1", "Row sums of a matrix or data frame."},
    {"colMeans", "base", "x, na.rm = FALSE, dims = 1", "Column means of a matrix or data frame."},
    {"rowMeans", "base", "x, na.rm = FALSE, dims = 1", "Row means of a matrix or data frame."},
    {"crossprod", "base", "x, y = x, ...", "t(x) %*% y, computed directly."},
    {"solve", "base", "a, b, ...", "Solves a linear system, or inverts a matrix."},
    {"det", "base", "x, ...", "The determinant of a matrix."},
    {"diag", "base", "x = 1, nrow, ncol, names = TRUE", "The diagonal of a matrix, or an identity matrix."},
    {"table", "base", "..., exclude, useNA = c(\"no\", \"ifany\", \"always\"), dnn, deparse.level = 1",
     "Counts occurrences, cross-classifying by every argument."},
    {"tabulate", "base", "bin, nbins = max(1L, bin, na.rm = TRUE)", "Counts integer bins, fast."},
    {"nargs", "base", "", "How many arguments the enclosing call was given."},
    {"missing", "base", "x", "Tests whether a formal argument was supplied."},
    {"match.arg", "base", "arg, choices, several.ok = FALSE", "Matches an argument against its allowed values."},
    {"match.call", "base", "definition = sys.function(sys.parent()), call = sys.call(sys.parent()), expand.dots = TRUE",
     "The current call with its arguments matched to formals."},
    {"sys.call", "base", "which = 0", "The call of a frame on the stack."},
    {"sys.function", "base", "which = 0", "The function being evaluated in a frame."},
    {"parent.frame", "base", "n = 1", "The environment of the calling function."},
    {"environment", "base", "fun = NULL", "The environment of a function or of the current call."},
    {"new.env", "base", "hash = TRUE, parent = parent.frame(), size = 29L", "Creates a fresh environment."},
    {"globalenv", "base", "", "The global environment."},
    {"emptyenv", "base", "", "The empty environment, at the top of every chain."},
    {"exists", "base", "x, where = -1, envir = as.environment(where), frame, mode = \"any\", inherits = TRUE",
     "Tests whether a name is bound in an environment."},
    {"get", "base", "x, pos = -1, envir = as.environment(pos), mode = \"any\", inherits = TRUE",
     "Looks up a name computed at run time."},
    {"get0", "base", "x, envir = as.environment(-1), mode = \"any\", inherits = TRUE, ifnotfound = NULL",
     "get() with a default instead of an error."},
    {"mget", "base", "x, envir = as.environment(-1), mode = \"any\", ifnotfound, inherits = FALSE",
     "Looks up several names at once."},
    {"assign", "base", "x, value, pos = -1, envir = as.environment(pos), inherits = FALSE, immediate = TRUE",
     "Binds a name computed at run time."},
    {"rm", "base", "..., list = character(), pos = -1, envir = as.environment(pos), inherits = FALSE",
     "Removes bindings from an environment."},
    {"local", "base", "expr, envir = new.env()", "Evaluates an expression in its own environment."},
    {"eval", "base", "expr, envir = parent.frame(), enclos = if (is.list(envir) || is.pairlist(envir)) parent.frame() else baseenv()",
     "Evaluates a quoted expression."},
    {"quote", "base", "expr", "Returns its argument unevaluated."},
    {"substitute", "base", "expr, env", "The expression an argument was called with."},
    {"bquote", "base", "expr, where = parent.frame(), splice = FALSE", "Quotes an expression, evaluating .() parts."},
    {"deparse", "base", "expr, width.cutoff = 60L, backtick = mode(expr) %in% c(\"call\", \"expression\", \"(\", \"function\"), control = c(\"keepNA\", \"keepInteger\", \"niceNames\", \"showAttributes\"), nlines = -1L", "Turns an expression back into source text."},
    {"parse", "base", "file = \"\", n = NULL, text = NULL, prompt = \"?\", keep.source = getOption(\"keep.source\"), srcfile = NULL, encoding = \"unknown\"", "Parses R source into expressions."},
    {"body", "base", "fun = sys.function(sys.parent())", "The body of a function."},
    {"formals", "base", "fun = sys.function(sys.parent()), envir = parent.frame()", "The formal arguments of a function."},
    {"args", "base", "name", "A function with the same formals and an empty body, for printing."},
    {"Vectorize", "base", "FUN, vectorize.args = arg.names, SIMPLIFY = TRUE, USE.NAMES = TRUE",
     "Wraps a function so it maps over its arguments."},
    {"identity", "base", "x", "Returns its argument unchanged."},
    {"Sys.time", "base", "", "The current time, as a POSIXct."},
    {"Sys.Date", "base", "", "The current date, as a Date."},
    {"Sys.getenv", "base", "x = NULL, unset = \"\", names", "Reads environment variables."},
    {"Sys.setenv", "base", "...", "Sets environment variables."},
    {"Sys.sleep", "base", "time", "Pauses for a number of seconds."},
    {"date", "base", "", "The current date and time as a string."},
    {"as.Date", "base", "x, format, tryFormats = c(\"%Y-%m-%d\", \"%Y/%m/%d\"), optional = FALSE, ...",
     "Converts to a Date."},
    {"format.Date", "base", "x, format = \"%Y-%m-%d\", ...", "Formats a Date with a strftime pattern."},
    {"difftime", "base", "time1, time2, tz, units = c(\"auto\", \"secs\", \"mins\", \"hours\", \"days\", \"weeks\")",
     "The difference between two times."},
    {"strftime", "base", "x, format = \"\", tz = \"\", usetz = FALSE, ...", "Formats a time as a string."},
    {"strptime", "base", "x, format, tz = \"\"", "Parses a string as a time."},
    {"file.path", "base", "..., fsep = .Platform$file.sep", "Joins path components with the platform separator."},
    {"file.exists", "base", "...", "Tests whether files exist."},
    {"basename", "base", "path", "The file name part of a path."},
    {"dirname", "base", "path", "The directory part of a path."},
    {"normalizePath", "base", "path, winslash = \"\\\\\", mustWork = NA", "Expands a path to its canonical form."},
    {"list.files", "base", "path = \".\", pattern = NULL, all.files = FALSE, full.names = FALSE, recursive = FALSE",
     "Lists the files in a directory."},
    {"readLines", "base", "con = stdin(), n = -1L, ok = TRUE, warn = TRUE, encoding = \"unknown\", skipNul = FALSE",
     "Reads a text file as a character vector, one element per line."},
    {"writeLines", "base", "text, con = stdout(), sep = \"\\n\", useBytes = FALSE",
     "Writes a character vector as lines."},
    {"readRDS", "base", "file, refhook = NULL", "Reads one serialized R object back."},
    {"saveRDS", "base", "object, file = \"\", ascii = FALSE, version = NULL, compress = TRUE, refhook = NULL",
     "Serializes one R object to a file."},
    {"file", "base", "description = \"\", open = \"\", blocking = TRUE, encoding = getOption(\"encoding\")",
     "Opens a file connection."},
    {"close", "base", "con, ...", "Closes a connection."},
    {"source", "base", "file, local = FALSE, echo = verbose, ...", "Parses and evaluates an R file."},
    {"library", "base", "package, help, pos = 2, lib.loc = NULL, character.only = FALSE, ...",
     "Attaches a package, stopping if it is not installed."},
    {"require", "base", "package, lib.loc = NULL, quietly = FALSE, character.only = FALSE, mask.ok, exclude",
     "Attaches a package, returning FALSE instead of stopping."},
    {"requireNamespace", "base", "package, ..., quietly = FALSE", "Loads a namespace without attaching it."},
    {"options", "base", "...", "Gets or sets global options."},
    {"getOption", "base", "x, default = NULL", "Reads one global option."},
    {"set.seed", "base", "seed, kind = NULL, normal.kind = NULL, sample.kind = NULL",
     "Seeds the random number generator, making a run reproducible."},
    {"return", "base", "value = NULL", "Returns from the enclosing function."},
    {"UseMethod", "base", "generic, object", "Dispatches to an S3 method."},
    {"NextMethod", "base", "generic = NULL, object = NULL, ...", "Calls the next method in the S3 chain."},
    {"unclass", "base", "x", "Drops the class attribute."},
    {"merge", "base", "x, y, by, by.x = by, by.y = by, all = FALSE, all.x = all, all.y = all, sort = TRUE, ...",
     "Joins two data frames on shared columns."},
    {"subset", "base", "x, subset, select, drop = FALSE, ...",
     "Selects rows and columns using expressions evaluated inside the data."},
    {"transform", "base", "`_data`, ...", "Adds or replaces columns of a data frame."},
    {"with", "base", "data, expr, ...", "Evaluates an expression with a data frame's columns in scope."},
    {"within", "base", "data, expr, ...", "Like with(), but returns the modified data."},
    {"attach", "base", "what, pos = 2L, name = deparse1(substitute(what)), warn.conflicts = TRUE",
     "Puts a data frame on the search path -- rarely a good idea."},
    {"median", "stats", "x, na.rm = FALSE, ...", "The median of a vector."},
    {"var", "stats", "x, y = NULL, na.rm = FALSE, use", "The sample variance, or a covariance matrix."},
    {"sd", "stats", "x, na.rm = FALSE", "The sample standard deviation."},
    {"cor", "stats", "x, y = NULL, use = \"everything\", method = c(\"pearson\", \"kendall\", \"spearman\")",
     "The correlation between vectors or the columns of a matrix."},
    {"cov", "stats", "x, y = NULL, use = \"everything\", method = c(\"pearson\", \"kendall\", \"spearman\")",
     "The covariance between vectors or the columns of a matrix."},
    {"quantile", "stats", "x, probs = seq(0, 1, 0.25), na.rm = FALSE, names = TRUE, type = 7, ...",
     "Sample quantiles."},
    {"summary", "base", "object, ...", "A summary of an object, dispatching on its class."},
    {"lm", "stats", "formula, data, subset, weights, na.action, method = \"qr\", model = TRUE, ...",
     "Fits a linear model by least squares."},
    {"glm", "stats", "formula, family = gaussian, data, weights, subset, na.action, start = NULL, ...",
     "Fits a generalized linear model."},
    {"predict", "stats", "object, ...", "Predictions from a fitted model."},
    {"residuals", "stats", "object, ...", "The residuals of a fitted model."},
    {"fitted", "stats", "object, ...", "The fitted values of a model."},
    {"coef", "stats", "object, ...", "The coefficients of a fitted model."},
    {"anova", "stats", "object, ...", "Analysis of variance tables for fitted models."},
    {"confint", "stats", "object, parm, level = 0.95, ...", "Confidence intervals for model parameters."},
    {"t.test", "stats", "x, ...", "Student's t-test, one sample, two sample or paired."},
    {"wilcox.test", "stats", "x, ...", "The Wilcoxon rank sum and signed rank tests."},
    {"chisq.test", "stats", "x, y = NULL, correct = TRUE, p = rep(1/length(x), length(x)), rescale.p = FALSE, simulate.p.value = FALSE, B = 2000",
     "Pearson's chi-squared test."},
    {"shapiro.test", "stats", "x", "The Shapiro-Wilk normality test."},
    {"aov", "stats", "formula, data = NULL, projections = FALSE, qr = TRUE, contrasts = NULL, ...",
     "Fits an analysis of variance model."},
    {"formula", "stats", "x, env = parent.frame(), ...", "Creates a model formula."},
    {"na.omit", "stats", "object, ...", "Drops the rows or elements containing NA."},
    {"complete.cases", "stats", "...", "TRUE for each row with no NA in it."},
    {"aggregate", "stats", "x, ...", "Splits data into groups and applies a summary to each."},
    {"runif", "stats", "n, min = 0, max = 1", "Random draws from a uniform distribution."},
    {"rnorm", "stats", "n, mean = 0, sd = 1", "Random draws from a normal distribution."},
    {"rbinom", "stats", "n, size, prob", "Random draws from a binomial distribution."},
    {"rpois", "stats", "n, lambda", "Random draws from a Poisson distribution."},
    {"sample", "base", "x, size, replace = FALSE, prob = NULL", "A random sample, with or without replacement."},
    {"dnorm", "stats", "x, mean = 0, sd = 1, log = FALSE", "The normal density."},
    {"pnorm", "stats", "q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE",
     "The normal cumulative distribution function."},
    {"qnorm", "stats", "p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE", "The normal quantile function."},
    {"optim", "stats", "par, fn, gr = NULL, ..., method = c(\"Nelder-Mead\", \"BFGS\", \"CG\", \"L-BFGS-B\", \"SANN\", \"Brent\")",
     "General-purpose numerical optimization."},
    {"optimize", "stats", "f, interval, ..., lower = min(interval), upper = max(interval), maximum = FALSE, tol",
     "One-dimensional optimization."},
    {"uniroot", "stats", "f, interval, ..., lower = min(interval), upper = max(interval), tol",
     "Finds a root of a one-dimensional function."},
    {"integrate", "stats", "f, lower, upper, ..., subdivisions = 100L", "Adaptive numerical integration."},
    {"density", "stats", "x, bw = \"nrd0\", adjust = 1, kernel = \"gaussian\", ...", "Kernel density estimate."},
    {"setNames", "stats", "object = nm, nm", "Returns an object with its names set, inline."},

    // utils
    {"read.csv", "utils", "file, header = TRUE, sep = \",\", quote = \"\\\"\", dec = \".\", fill = TRUE, comment.char = \"\", ...",
     "Reads a comma-separated file into a data frame."},
    {"read.table", "utils", "file, header = FALSE, sep = \"\", quote = \"\\\"'\", dec = \".\", ...",
     "Reads a whitespace-separated file into a data frame."},
    {"write.csv", "utils", "x, file = \"\", row.names = TRUE, ...", "Writes a data frame as a comma-separated file."},
    {"write.table", "utils", "x, file = \"\", append = FALSE, quote = TRUE, sep = \" \", eol = \"\\n\", na = \"NA\", dec = \".\", row.names = TRUE, col.names = TRUE, qmethod = c(\"escape\", \"double\"), fileEncoding = \"\"",
     "Writes a data frame as a text file."},
    {"str", "utils", "object, ...", "Compactly displays the structure of an object."},
    {"install.packages", "utils", "pkgs, lib, repos = getOption(\"repos\"), ...", "Downloads and installs packages."},
    {"installed.packages", "utils", "lib.loc = NULL, priority = NULL, ...", "A matrix of the installed packages."},
    {"sessionInfo", "utils", "package = NULL", "R version, platform and attached packages."},
    {"modifyList", "utils", "x, val, keep.null = FALSE", "Merges one list into another, recursively."},
    {"capture.output", "utils", "..., file = NULL, append = FALSE, type = c(\"output\", \"message\"), split = FALSE",
     "Captures printed output as a character vector."},
    {"packageVersion", "utils", "pkg, lib.loc = NULL", "The version of an installed package."},
    {"data", "utils", "..., list = character(), package = NULL, lib.loc = NULL, verbose = FALSE, envir = .GlobalEnv",
     "Loads a data set shipped with a package."},

    // graphics / grDevices
    {"plot", "graphics", "x, y, ...", "The generic plotting function."},
    {"lines", "graphics", "x, y = NULL, type = \"l\", ...", "Adds lines to an existing plot."},
    {"points", "graphics", "x, y = NULL, type = \"p\", ...", "Adds points to an existing plot."},
    {"abline", "graphics", "a = NULL, b = NULL, h = NULL, v = NULL, reg = NULL, coef = NULL, ...",
     "Adds a straight line to a plot."},
    {"hist", "graphics", "x, breaks = \"Sturges\", freq = NULL, main = NULL, xlab = NULL, ...", "Draws a histogram."},
    {"boxplot", "graphics", "x, ...", "Draws a box-and-whisker plot."},
    {"barplot", "graphics", "height, ...", "Draws a bar plot."},
    {"legend", "graphics", "x, y = NULL, legend, fill = NULL, col = par(\"col\"), lty, lwd, pch, bty = \"o\", ...",
     "Adds a legend to a plot."},
    {"text", "graphics", "x, y = NULL, labels = seq_along(x$x), adj = NULL, pos = NULL, cex = 1, col = NULL, ...",
     "Draws text at coordinates on a plot."},
    {"par", "graphics", "...", "Gets or sets base graphics parameters."},
    {"png", "grDevices", "filename = \"Rplot%03d.png\", width = 480, height = 480, units = \"px\", res = NA, ...",
     "Opens a PNG graphics device."},
    {"pdf", "grDevices", "file = \"Rplots.pdf\", width = 7, height = 7, onefile = TRUE, ...",
     "Opens a PDF graphics device."},
    {"dev.off", "grDevices", "which = dev.cur()", "Closes the current graphics device, writing the file."},
    {"colors", "grDevices", "", "The names of the built-in colours."},
    {"rgb", "grDevices", "red, green, blue, alpha, names = NULL, maxColorValue = 1", "Builds a colour from components."},

    // methods (S4) and reference classes
    {"setClass", "methods", "Class, representation = list(), prototype = NULL, contains = character(), validity = NULL, access = list(), where = topenv(parent.frame()), version = .newExternalptr(), sealed = FALSE, package = getPackageName(where), S3methods = FALSE, slots",
     "Defines an S4 class."},
    {"setGeneric", "methods", "name, def = NULL, group = list(), valueClass = character(), where = topenv(parent.frame()), package = NULL, signature = NULL, useAsDefault = NULL, genericFunction = NULL, simpleInheritanceOnly = NULL",
     "Declares an S4 generic."},
    {"setMethod", "methods", "f, signature = character(), definition, where = topenv(parent.frame()), valueClass = NULL, sealed = FALSE",
     "Defines an S4 method for a generic."},
    {"setValidity", "methods", "Class, method, where = topenv(parent.frame())", "Attaches a validity function to an S4 class."},
    {"new", "methods", "Class, ...", "Constructs an instance of an S4 class."},
    {"validObject", "methods", "object, test = FALSE, complete = FALSE", "Checks an S4 object against its validity function."},
    {"slot", "methods", "object, name", "Gets one slot of an S4 object."},
    {"slotNames", "methods", "x", "The slot names of an S4 class."},
    {"is", "methods", "object, class2", "Tests class membership, following S4 inheritance."},
    {"setRefClass", "methods", "Class, fields = character(), contains = character(), methods = list(), where, ...",
     "Defines a reference (R5) class."},
    {"standardGeneric", "methods", "f, fdef", "Dispatches an S4 generic -- the body of every setGeneric default."},
};

// --- Reserved words, constants, operators ------------------------------

const std::vector<RLspVocabEntry> kKeywords = {
    {"if", "if (cond) expr", "Conditional evaluation. The condition must be one non-NA TRUE or FALSE."},
    {"else", "else expr", "The branch taken when an `if` condition is FALSE."},
    {"for", "for (var in seq) expr", "Iterates over the elements of a vector or list."},
    {"while", "while (cond) expr", "Repeats while a condition stays TRUE."},
    {"repeat", "repeat expr", "Repeats forever, until a `break`."},
    {"break", "break", "Leaves the innermost loop."},
    {"next", "next", "Skips to the next iteration of the innermost loop."},
    {"function", "function(args) body", "Creates a function. The shorthand is \\(args) body."},
    {"return", "return(value)", "Returns from the enclosing function. R returns the last value anyway."},
    {"in", "for (x in xs)", "Separates the loop variable from the sequence in a `for` header."},
};

const std::vector<RLspVocabEntry> kConstants = {
    {"TRUE", "logical", "Logical true. Prefer it to the rebindable abbreviation T."},
    {"FALSE", "logical", "Logical false. Prefer it to the rebindable abbreviation F."},
    {"NULL", "NULL", "The empty object. A zero-length list slot, not a missing value."},
    {"NA", "logical", "A missing value. Compare with is.na(), never with ==."},
    {"NA_integer_", "integer", "A missing value of integer type."},
    {"NA_real_", "double", "A missing value of double type."},
    {"NA_character_", "character", "A missing value of character type."},
    {"Inf", "double", "Positive infinity."},
    {"NaN", "double", "Not a number, the result of 0/0."},
    {"pi", "double", "The constant pi, 3.141593."},
    {"T", "logical", "An abbreviation of TRUE -- an ordinary variable, and so rebindable. Write TRUE."},
    {"F", "logical", "An abbreviation of FALSE -- an ordinary variable, and so rebindable. Write FALSE."},
    {"LETTERS", "character[26]", "The 26 upper-case letters."},
    {"letters", "character[26]", "The 26 lower-case letters."},
    {"month.name", "character[12]", "The English month names."},
    {"month.abb", "character[12]", "The three-letter English month abbreviations."},
    {".Machine", "list", "Numeric characteristics of the machine, such as .Machine$double.eps."},
};

const std::vector<RLspVocabEntry> kOperators = {
    {"<-", "assignment", "Assigns in the current environment. R's ordinary assignment."},
    {"<<-", "assignment", "Assigns in an enclosing environment, creating a global binding if there is none."},
    {"->", "assignment", "Right assignment: value -> name."},
    {"->>", "assignment", "Right assignment into an enclosing environment."},
    {"=", "assignment", "Assignment at statement level, and the named-argument marker inside a call."},
    {"%in%", "logical", "Elementwise membership: TRUE for each element of the left found in the right."},
    {"%%", "numeric", "Modulo: the remainder after integer division."},
    {"%/%", "numeric", "Integer division, rounding toward minus infinity."},
    {"%*%", "matrix", "Matrix multiplication."},
    {"%o%", "matrix", "Outer product."},
    {"|>", "pipe", "The native pipe: x |> f() is f(x)."},
    {"~", "formula", "Builds a formula: response ~ predictors. Its sides are not evaluated."},
    {"::", "namespace", "Reads an exported name from a package without attaching it."},
    {":::", "namespace", "Reads an internal name from a package's namespace."},
    {"$", "extract", "Extracts a named element of a list or data frame, with partial matching."},
    {"@", "slot", "Extracts a slot of an S4 object."},
    {"[", "subset", "Subsets, keeping the type of the object."},
    {"[[", "extract", "Extracts a single element, dropping one level of structure."},
    {"&&", "logical", "Scalar and, short-circuiting. Errors on a vector since R 4.3."},
    {"||", "logical", "Scalar or, short-circuiting. Errors on a vector since R 4.3."},
    {"&", "logical", "Elementwise and, over whole vectors."},
    {"|", "logical", "Elementwise or, over whole vectors."},
    {"!", "logical", "Negation, elementwise."},
    {":", "sequence", "An integer sequence from left to right -- counting down when left > right."},
    {"^", "numeric", "Exponentiation, right-associative: 2^3^2 is 2^(3^2)."},
    {"**", "numeric", "A deprecated spelling of '^'. R still parses it; write '^'."},
};

const std::vector<RLspVocabEntry> kRoxygen = {
    {"param", "@param name description", "Documents one formal argument."},
    {"return", "@return description", "Documents the value the function returns."},
    {"returns", "@returns description", "Documents the value the function returns (the newer spelling)."},
    {"title", "@title text", "The one-line title of the help page."},
    {"description", "@description text", "The opening paragraph of the help page."},
    {"details", "@details text", "The longer explanation, after the description."},
    {"examples", "@examples code", "Runnable example code for the help page."},
    {"examplesIf", "@examplesIf condition", "Examples that only run when a condition holds."},
    {"export", "@export", "Adds the object to the package's NAMESPACE."},
    {"exportS3Method", "@exportS3Method generic class", "Registers an S3 method in the NAMESPACE."},
    {"import", "@import package", "Imports a whole package into the namespace."},
    {"importFrom", "@importFrom package name", "Imports named objects from a package."},
    {"inheritParams", "@inheritParams function", "Reuses another function's parameter documentation."},
    {"seealso", "@seealso links", "Related help pages."},
    {"family", "@family name", "Cross-links every function in a named family."},
    {"rdname", "@rdname name", "Writes this documentation into a named .Rd file."},
    {"name", "@name name", "The name of the help topic."},
    {"aliases", "@aliases names", "Extra names the help topic answers to."},
    {"keywords", "@keywords words", "Index keywords for the help page."},
    {"author", "@author name", "The author of the documented object."},
    {"references", "@references text", "Literature references."},
    {"section", "@section Title:", "Adds a custom section to the help page."},
    {"noRd", "@noRd", "Documents the object for readers but writes no .Rd file."},
    {"slot", "@slot name description", "Documents one slot of an S4 class."},
    {"field", "@field name description", "Documents one field of a reference or R6 class."},
    {"format", "@format description", "Describes the shape of a documented data set."},
    {"source", "@source text", "Where a documented data set came from."},
    {"describeIn", "@describeIn function text", "Documents this object on another function's page."},
    {"method", "@method generic class", "Declares an S3 method explicitly."},
    {"docType", "@docType type", "The documentation type (data, package, class)."},
    {"useDynLib", "@useDynLib package", "Loads compiled code from the package's shared library."},
    {"concept", "@concept text", "An index concept for help search."},
    {"md", "@md", "Interprets the block as Markdown (the default in modern roxygen2)."},
    {"eval", "@eval expression", "Inserts documentation generated by evaluating R code."},
    {"include", "@include file", "Declares a collation dependency on another source file."},
    {"order", "@order n", "Orders blocks that share an .Rd file."},
    {"inherit", "@inherit source fields", "Inherits documentation sections from another topic."},
};

// The base distribution: the packages whose exports this server knows,
// and so the ones whose `library()` does *not* switch off the
// undefined-variable check (see r_lsp.h).
const char *const kBasePackages[] = {"base",  "stats",  "utils",  "graphics", "grDevices",
                                     "methods", "tools", "parallel", "compiler", "datasets",
                                     "grid",  "splines", "stats4", "tcltk"};

// Offered after `library(`. The base distribution first (always
// available), then the packages people most often reach for -- labels
// only: the server knows nothing about what they export.
const std::vector<RLspVocabEntry> kPackages = {
    {"base", "base R", "The R language itself: always attached."},
    {"stats", "base R", "Statistical functions, distributions and models."},
    {"utils", "base R", "Utilities: reading files, installing packages, str()."},
    {"graphics", "base R", "Base graphics: plot(), hist(), lines()."},
    {"grDevices", "base R", "Graphics devices and colours."},
    {"methods", "base R", "S4 classes and methods."},
    {"tools", "base R", "Package development tools."},
    {"parallel", "base R", "Parallel apply functions and clusters."},
    {"compiler", "base R", "The byte-code compiler."},
    {"datasets", "base R", "The example data sets."},
    {"grid", "base R", "The grid graphics engine, under lattice and ggplot2."},
    {"splines", "base R", "Regression spline bases."},
    {"MASS", "recommended", "Functions from Modern Applied Statistics with S."},
    {"Matrix", "recommended", "Sparse and dense matrix classes."},
    {"lattice", "recommended", "Trellis graphics."},
    {"survival", "recommended", "Survival analysis."},
    {"nlme", "recommended", "Linear and nonlinear mixed effects models."},
    {"ggplot2", "CRAN", "The grammar of graphics."},
    {"dplyr", "CRAN", "Data frame verbs: filter, mutate, summarise."},
    {"tidyr", "CRAN", "Reshaping data between long and wide."},
    {"readr", "CRAN", "Fast, predictable file reading."},
    {"purrr", "CRAN", "Functional programming tools: map and friends."},
    {"stringr", "CRAN", "Consistent string functions over stringi."},
    {"tibble", "CRAN", "A modern take on the data frame."},
    {"data.table", "CRAN", "Fast aggregation and joins with its own [ ] syntax."},
    {"lubridate", "CRAN", "Dates and times."},
    {"shiny", "CRAN", "Reactive web applications in R."},
    {"knitr", "CRAN", "Literate programming and report generation."},
    {"rmarkdown", "CRAN", "R Markdown documents."},
    {"testthat", "CRAN", "Unit testing."},
    {"devtools", "CRAN", "Package development workflow."},
    {"usethis", "CRAN", "Project and package setup automation."},
    {"roxygen2", "CRAN", "Documentation from source comments."},
    {"Rcpp", "CRAN", "Seamless R and C++ integration."},
    {"R6", "CRAN", "Encapsulated object-oriented programming."},
    {"jsonlite", "CRAN", "JSON parsing and generation."},
    {"httr2", "CRAN", "HTTP requests."},
    {"DBI", "CRAN", "A database interface."},
    {"future", "CRAN", "Parallel and distributed evaluation."},
    {"targets", "CRAN", "Reproducible analysis pipelines."},
};

}  // namespace

const std::vector<RLspFunctionEntry> &RLspFunctionVocab() { return kFunctions; }

const RLspFunctionEntry *RLspFindFunction(const std::string &name) {
    // Built once, on first use: the table is a hand-maintained literal
    // grouped by topic rather than sorted, so a linear scan per lookup
    // would be the wrong shape for hover and completion both.
    static const std::map<std::string, const RLspFunctionEntry *> index = [] {
        std::map<std::string, const RLspFunctionEntry *> built;
        for (const RLspFunctionEntry &entry : kFunctions) built.emplace(entry.name, &entry);
        return built;
    }();
    const auto it = index.find(name);
    return it == index.end() ? nullptr : it->second;
}

const std::vector<RLspVocabEntry> &RLspKeywordVocab() { return kKeywords; }
const std::vector<RLspVocabEntry> &RLspConstantVocab() { return kConstants; }
const std::vector<RLspVocabEntry> &RLspOperatorVocab() { return kOperators; }
const std::vector<RLspVocabEntry> &RLspRoxygenVocab() { return kRoxygen; }
const std::vector<RLspVocabEntry> &RLspPackageVocab() { return kPackages; }

bool RLspIsBasePackage(const std::string &name) {
    for (const char *pkg : kBasePackages) {
        if (name == pkg) return true;
    }
    return false;
}
